### ISSUE TITLE
Discrepancies when training seq2seq_tds model (unknown failure; slowness)

### ISSUE THREAD

**Issue by nimz** [facebookresearch/wav2letter#388] opened 2019-08-28 06:56 UTC
When I run the recipe in `recipes/models/seq2seq_tds/librispeech/train.cfg` (after having successfully run `recipes/models/seq2seq_tds/librispeech/prepare.py` and updating paths appropriately without changing anything else) with the command `mpirun -n 8 build/Train train --flagsfile recipes/models/seq2seq_tds/librispeech/train.cfg --enable_distributed=true`, after the message `Initialized NCCL 2.3.4 successfully!` I get the following error message (from each process):

```*** Aborted at 1566969876 (unix time) try "date -d @1566969876" if you are using GNU date ***                                                                                                                            |
PC: @     0x7ffc9e7fdb12 ([vdso]+0xb11)                                                                                                                                                                                  |
*** SIGTERM (@0x0) received by PID 6561 (TID 0x7fa503a2d640) from PID 0; stack trace: ***                                                                                                                                |
    @     0x7fa4b1137060 (unknown)                                                                                                                                                                                       |
    @     0x7ffc9e7fdb12 ([vdso]+0xb11)                                                                                                                                                                                  |
    @     0x7fa4b11f9ba6 (unknown)                                                                                                                                                                                       |
    @     0x7fa4973e0cfe (unknown)                                                                                                                                                                                       |
    @     0x7fa497470543 (unknown)                                                                                                                                                                                       |
    @     0x7fa49738c42c (unknown)                                                                                                                                                                                       |
    @     0x7fa4972cbad8 (unknown)                                                                                                                                                                                       |
    @     0x7fa4974008f2 cuMemFree_v2                                                                                                                                                                                    |
    @     0x7fa4987caf94 (unknown)                                                                                                                                                                                       |
    @     0x7fa498802b81 (unknown)                                                                                                                                                                                       |
    @     0x7fa498634ae9 (unknown)                                                                                                                                                                                       |
    @     0x7fa498635031 (unknown)                                                                                                                                                                                       |
    @     0x7fa4cd760de1 cuda::matmul<>()                                                                                                                                                                                |
    @     0x7fa4cd84da8f af_sparse_matmul()                                                                                                                                                                              |
    @     0x7fa4cd84eef5 af_matmul                                                                                                                                                                                       |
    @     0x7fa4cdb3c1b7 af::matmulTN()                                                                                                                                                                                  |
    @     0x55d0d65d6ea2 _ZNSt17_Function_handlerIFvRSt6vectorIN2fl8VariableESaIS2_EERKS2_EZNS1_9embeddingES7_S7_EUlS5_S7_E_E9_M_invokeERKSt9_Any_dataS5_S7_                                                             |
    @     0x55d0d65d10f5 fl::Variable::backward()                                                                                                                                                                        |
    @     0x55d0d65d164f fl::Variable::backward()                                                                                                                                                                        |
    @     0x55d0d63bcdcf _ZZ4mainENKUlSt10shared_ptrIN2fl6ModuleEES_IN3w2l17SequenceCriterionEES_INS3_10W2lDatasetEES_INS0_19FirstOrderOptimizerEES9_ddbiE3_clES2_S5_S7_S9_S9_ddbi                                       |
    @     0x55d0d6365554 main                                                                                                                                                                                            |
    @     0x7fa4b11242e1 __libc_start_main                                                                                                                                                                               |
    @     0x55d0d63b63ba _start                                                                                                                                                                                          |
    @                0x0 (unknown)                                                                                                                                                                                       |
--------------------------------------------------------------------------                                                                                                                                               |
mpirun noticed that process rank 3 with PID 0 on node wav2letter-vm-1 exited on signal 6 (Aborted).                                                                                                                      |
```

The training script terminates with this failure. This is on a virtual machine with 8 V100 GPUs (each with 16 GB of memory), 64 vCPUs, and 240 GB of RAM. This happens every time I run the above (i.e. not a transient issue).

If I instead run `mpirun -n 7 build/Train train --flagsfile recipes/models/seq2seq_tds/librispeech/train.cfg --enable_distributed=true`, training proceeds with no errors (only 7 of the 8 GPUs get used. I also checked and only about 40 GB of CPU RAM are in use). However, the speed of training is much slower than reported in the "Sequence-to-Sequence Speech Recognition with
Time-Depth Separable Convolutions" paper: the paper reports a training speed of 7 minutes per epoch, whereas each epoch takes almost 19 minutes for me.

**Comment by tlikhomanenko** [comment] 2019-08-29 03:07
Hi @nimz,

Could you send the log where detailed timing is printed (several epochs)?

**Comment by nimz** [comment] 2019-09-02 23:22
Hi @tlikhomanenko, sorry for the delay. Here is a log for 10 epochs:

```
mpirun -n 7 build/Train train --flagsfile recipes/models/seq2seq_tds/librispeech/train.cfg --enable_distributed=true --logtostderr=1 --minloglevel=0
I0902 19:30:25.449877 15071 Train.cpp:58] Reading flags from file recipes/models/seq2seq_tds/librispeech/train.cfg
I0902 19:30:25.449877 15072 Train.cpp:58] Reading flags from file recipes/models/seq2seq_tds/librispeech/train.cfg
I0902 19:30:25.449877 15073 Train.cpp:58] Reading flags from file recipes/models/seq2seq_tds/librispeech/train.cfg
I0902 19:30:25.449875 15074 Train.cpp:58] Reading flags from file recipes/models/seq2seq_tds/librispeech/train.cfg
I0902 19:30:25.449874 15075 Train.cpp:58] Reading flags from file recipes/models/seq2seq_tds/librispeech/train.cfg
I0902 19:30:25.449872 15076 Train.cpp:58] Reading flags from file recipes/models/seq2seq_tds/librispeech/train.cfg
I0902 19:30:25.450850 15077 Train.cpp:58] Reading flags from file recipes/models/seq2seq_tds/librispeech/train.cfg
Initialized NCCL 2.3.4 successfully!
I0902 19:30:28.189277 15071 Train.cpp:137] Gflags after parsing
--flagfile=; --fromenv=; --tryfromenv=; --undefok=; --tab_completion_columns=80; --tab_completion_word=; --help=false; --helpfull=false; --helpmatch=; --helpon=; --helppackage=false; --helpshort=false; --helpxml=false; --version=false; --adambeta1=0.90000000000000002; --adambeta2=0.999; --am=; --arch=network.arch; --archdir=/home/nimz/wav2letter/recipes/models/seq2seq_tds/librispeech; --attention=keyvalue; --attentionthreshold=0; --attnWindow=softPretrain; --attnconvchannel=0; --attnconvkernel=0; --attndim=0; --batchsize=16; --beamsize=2500; --beamthreshold=25; --blobdata=false; --channels=1; --criterion=seq2seq; --critoptim=sgd; --datadir=; --dataorder=output_spiral; --decoderattnround=1; --decoderdropout=0; --decoderrnnlayer=1; --decodertype=wrd; --devwin=0; --emission_dir=; --enable_distributed=true; --encoderdim=512; --eostoken=true; --everstoredb=false; --fftcachesize=1; --filterbanks=80; --flagsfile=recipes/models/seq2seq_tds/librispeech/train.cfg; --framesizems=25; --framestridems=10; --gamma=0.5; --gumbeltemperature=1; --hardselection=1; --input=flac; --inputbinsize=25; --inputfeeding=false; --iter=200; --itersave=false; --labelsmooth=0.050000000000000003; --leftWindowSize=50; --lexicon=/home/nimz/wav2letter/seq2seq_tds_librispeech/am/librispeech-train+dev-unigram-10000-nbest10.lexicon; --linlr=-1; --linlrcrit=-1; --linseg=0; --lm=; --lm_memory=5000; --lm_vocab=; --lmtype=kenlm; --lmweight=0; --localnrmlleftctx=0; --localnrmlrightctx=0; --logadd=false; --lr=0.050000000000000003; --lrcrit=0.050000000000000003; --maxdecoderoutputlen=120; --maxgradnorm=15; --maxisz=9223372036854775807; --maxload=-1; --maxrate=10; --maxsil=50; --maxtsz=9223372036854775807; --maxword=-1; --melfloor=1; --memstepsize=4194304; --mfcc=false; --mfcccoeffs=13; --mfsc=true; --minisz=0; --minrate=3; --minsil=0; --mintsz=0; --momentum=0; --netoptim=sgd; --noresample=false; --nthread=6; --nthread_decoder=1; --onorm=none; --optimepsilon=1e-08; --optimrho=0.90000000000000002; --outputbinsize=5; --pctteacherforcing=99; --pcttraineval=1; --pow=false; --pretrainWindow=3; --replabel=0; --reportiters=0; --rightWindowSize=50; --rndv_filepath=; --rundir=/home/nimz/wav2letter/tds_run; --runname=seq2seq_tds_distributed; --samplerate=16000; --sampletarget=0.01; --samplingstrategy=rand; --sclite=; --seed=0; --show=false; --showletters=false; --silweight=0; --smearing=none; --smoothingtemperature=1; --softselection=inf; --softwoffset=10; --softwrate=5; --softwstd=4; --sqnorm=false; --stepsize=40; --surround=; --tag=; --target=ltr; --test=; --tokens=librispeech-train-all-unigram-10000.tokens; --tokensdir=/home/nimz/wav2letter/seq2seq_tds_librispeech/am; --train=/home/nimz/wav2letter/librispeech/lists/train-clean-100.lst,/home/nimz/wav2letter/librispeech/lists/train-clean-360.lst,/home/nimz/wav2letter/librispeech/lists/train-other-500.lst; --trainWithWindow=true; --transdiag=0; --unkweight=-inf; --uselexicon=true; --usewordpiece=true; --valid=dev-clean:/home/nimz/wav2letter/librispeech/lists/dev-clean.lst,dev-other:/home/nimz/wav2letter/librispeech/lists/dev-other.lst; --weightdecay=0; --wordscore=0; --wordseparator=_; --world_rank=0; --world_size=1; --alsologtoemail=; --alsologtostderr=false; --colorlogtostderr=false; --drop_log_memory=true; --log_backtrace_at=; --log_dir=; --log_link=; --log_prefix=true; --logbuflevel=0; --logbufsecs=30; --logemaillevel=999; --logmailer=/bin/mail; --logtostderr=true; --max_log_size=1800; --minloglevel=0; --stderrthreshold=2; --stop_logging_if_full_disk=false; --symbolize_stacktrace=true; --v=0; --vmodule=;
I0902 19:30:28.189323 15071 Train.cpp:138] Experiment path: /home/nimz/wav2letter/tds_run/seq2seq_tds_distributed
I0902 19:30:28.189327 15071 Train.cpp:139] Experiment runidx: 1
I0902 19:30:28.189374 15072 Train.cpp:183] Number of classes (network): 9998
I0902 19:30:28.190791 15073 Train.cpp:183] Number of classes (network): 9998
I0902 19:30:28.191263 15074 Train.cpp:183] Number of classes (network): 9998
I0902 19:30:28.191696 15075 Train.cpp:183] Number of classes (network): 9998
I0902 19:30:28.191946 15076 Train.cpp:183] Number of classes (network): 9998
I0902 19:30:28.192284 15077 Train.cpp:183] Number of classes (network): 9998
I0902 19:30:28.193465 15071 Train.cpp:183] Number of classes (network): 9998
I0902 19:30:29.072855 15071 Train.cpp:190] Number of words: 89612
I0902 19:30:29.078300 15072 Train.cpp:190] Number of words: 89612
I0902 19:30:29.078816 15076 Train.cpp:190] Number of words: 89612
I0902 19:30:29.081687 15075 Train.cpp:190] Number of words: 89612
I0902 19:30:29.082677 15073 Train.cpp:190] Number of words: 89612
I0902 19:30:29.082834 15074 Train.cpp:190] Number of words: 89612
I0902 19:30:29.083111 15077 Train.cpp:190] Number of words: 89612
I0902 19:30:29.124439 15071 Train.cpp:204] Loading architecture file from /home/nimz/wav2letter/recipes/models/seq2seq_tds/librispeech/network.arch
I0902 19:30:30.017938 15071 Train.cpp:225] [Network] Sequential [input -> (0) -> (1) -> (2) -> (3) -> (4) -> (5) -> (6) -> (7) -> (8) -> (9) -> (10) -> (11) -> (12) -> (13) -> (14) -> (15) -> (16) -> (17) -> (18) -> (19) -> (20) -> (21) -> (22) -> (23) -> (24) -> (25) -> (26) -> output]
        (0): View (-1 80 1 0)
        (1): Conv2D (1->10, 21x1, 2,1, SAME,SAME, 1, 1) (with bias)
        (2): ReLU
        (3): Dropout (0.200000)
        (4): LayerNorm ( axes : { 3 } )
        (5): Time-Depth Separable Block (21, 80, 10) [800 -> 800 -> 800]
        (6): Time-Depth Separable Block (21, 80, 10) [800 -> 800 -> 800]
        (7): Conv2D (10->14, 21x1, 2,1, SAME,SAME, 1, 1) (with bias)
        (8): ReLU
        (9): Dropout (0.200000)
        (10): LayerNorm ( axes : { 3 } )
        (11): Time-Depth Separable Block (21, 80, 14) [1120 -> 1120 -> 1120]
        (12): Time-Depth Separable Block (21, 80, 14) [1120 -> 1120 -> 1120]
        (13): Time-Depth Separable Block (21, 80, 14) [1120 -> 1120 -> 1120]
        (14): Conv2D (14->18, 21x1, 2,1, SAME,SAME, 1, 1) (with bias)
        (15): ReLU
        (16): Dropout (0.200000)
        (17): LayerNorm ( axes : { 3 } )
        (18): Time-Depth Separable Block (21, 80, 18) [1440 -> 1440 -> 1440]
        (19): Time-Depth Separable Block (21, 80, 18) [1440 -> 1440 -> 1440]
        (20): Time-Depth Separable Block (21, 80, 18) [1440 -> 1440 -> 1440]
        (21): Time-Depth Separable Block (21, 80, 18) [1440 -> 1440 -> 1440]
        (22): Time-Depth Separable Block (21, 80, 18) [1440 -> 1440 -> 1440]
        (23): Time-Depth Separable Block (21, 80, 18) [1440 -> 1440 -> 1440]
        (24): View (0 1440 1 0)
        (25): Reorder (1,0,3,2)
        (26): Linear (1440->1024) (with bias)
I0902 19:30:30.018028 15071 Train.cpp:226] [Network Params: 36538460]
I0902 19:30:30.018035 15071 Train.cpp:227] [Criterion] Seq2SeqCriterion
I0902 19:30:30.018175 15071 Train.cpp:235] [Network Optimizer] SGD
I0902 19:30:30.018185 15071 Train.cpp:236] [Criterion Optimizer] SGD
I0902 19:30:30.852586 15071 W2lListFilesDataset.cpp:137] 28539 files found.
I0902 19:30:30.866573 15072 W2lListFilesDataset.cpp:137] 28539 files found.
I0902 19:30:30.871268 15076 W2lListFilesDataset.cpp:137] 28539 files found.
I0902 19:30:30.871457 15075 W2lListFilesDataset.cpp:137] 28539 files found.
I0902 19:30:30.876329 15077 W2lListFilesDataset.cpp:137] 28539 files found.
I0902 19:30:30.877590 15074 W2lListFilesDataset.cpp:137] 28539 files found.
I0902 19:30:30.879782 15073 W2lListFilesDataset.cpp:137] 28539 files found.
I0902 19:30:32.671697 15071 W2lListFilesDataset.cpp:137] 104014 files found.
I0902 19:30:32.786880 15075 W2lListFilesDataset.cpp:137] 104014 files found.
I0902 19:30:32.788128 15074 W2lListFilesDataset.cpp:137] 104014 files found.
I0902 19:30:32.792546 15076 W2lListFilesDataset.cpp:137] 104014 files found.
I0902 19:30:32.792891 15072 W2lListFilesDataset.cpp:137] 104014 files found.
I0902 19:30:32.799572 15073 W2lListFilesDataset.cpp:137] 104014 files found.
I0902 19:30:32.806793 15077 W2lListFilesDataset.cpp:137] 104014 files found.
I0902 19:30:35.116490 15071 W2lListFilesDataset.cpp:137] 148688 files found.
I0902 19:30:35.122000 15071 Utils.cpp:102] Filtered 0/281241 samples
I0902 19:30:35.174966 15071 W2lListFilesDataset.cpp:62] Total batches (i.e. iters): 2512
I0902 19:30:35.352494 15074 W2lListFilesDataset.cpp:137] 148688 files found.
I0902 19:30:35.353580 15075 W2lListFilesDataset.cpp:137] 148688 files found.
I0902 19:30:35.356983 15074 Utils.cpp:102] Filtered 0/281241 samples
I0902 19:30:35.358084 15075 Utils.cpp:102] Filtered 0/281241 samples
I0902 19:30:35.375213 15076 W2lListFilesDataset.cpp:137] 148688 files found.
I0902 19:30:35.379230 15073 W2lListFilesDataset.cpp:137] 148688 files found.
I0902 19:30:35.379952 15076 Utils.cpp:102] Filtered 0/281241 samples
I0902 19:30:35.382081 15072 W2lListFilesDataset.cpp:137] 148688 files found.
I0902 19:30:35.383873 15073 Utils.cpp:102] Filtered 0/281241 samples
I0902 19:30:35.386729 15072 Utils.cpp:102] Filtered 0/281241 samples
I0902 19:30:35.389947 15077 W2lListFilesDataset.cpp:137] 148688 files found.
I0902 19:30:35.394714 15077 Utils.cpp:102] Filtered 0/281241 samples
I0902 19:30:35.415761 15074 W2lListFilesDataset.cpp:62] Total batches (i.e. iters): 2512
I0902 19:30:35.416342 15075 W2lListFilesDataset.cpp:62] Total batches (i.e. iters): 2512
I0902 19:30:35.437829 15076 W2lListFilesDataset.cpp:62] Total batches (i.e. iters): 2512
I0902 19:30:35.442566 15073 W2lListFilesDataset.cpp:62] Total batches (i.e. iters): 2512
I0902 19:30:35.445272 15072 W2lListFilesDataset.cpp:62] Total batches (i.e. iters): 2512
I0902 19:30:35.453490 15077 W2lListFilesDataset.cpp:62] Total batches (i.e. iters): 2512
I0902 19:30:35.509414 15071 W2lListFilesDataset.cpp:137] 2703 files found.
I0902 19:30:35.509510 15071 Utils.cpp:102] Filtered 0/2703 samples
I0902 19:30:35.509889 15071 W2lListFilesDataset.cpp:62] Total batches (i.e. iters): 25
I0902 19:30:35.734959 15075 W2lListFilesDataset.cpp:137] 2703 files found.
I0902 19:30:35.735054 15075 Utils.cpp:102] Filtered 0/2703 samples
I0902 19:30:35.735414 15075 W2lListFilesDataset.cpp:62] Total batches (i.e. iters): 25
I0902 19:30:35.739336 15074 W2lListFilesDataset.cpp:137] 2703 files found.
I0902 19:30:35.739403 15074 Utils.cpp:102] Filtered 0/2703 samples
I0902 19:30:35.739758 15074 W2lListFilesDataset.cpp:62] Total batches (i.e. iters): 25
I0902 19:30:35.761505 15076 W2lListFilesDataset.cpp:137] 2703 files found.
I0902 19:30:35.761580 15076 Utils.cpp:102] Filtered 0/2703 samples
I0902 19:30:35.761968 15076 W2lListFilesDataset.cpp:62] Total batches (i.e. iters): 25
I0902 19:30:35.766902 15073 W2lListFilesDataset.cpp:137] 2703 files found.
I0902 19:30:35.766999 15073 Utils.cpp:102] Filtered 0/2703 samples
I0902 19:30:35.767343 15073 W2lListFilesDataset.cpp:62] Total batches (i.e. iters): 25
I0902 19:30:35.767552 15072 W2lListFilesDataset.cpp:137] 2703 files found.
I0902 19:30:35.767621 15072 Utils.cpp:102] Filtered 0/2703 samples
I0902 19:30:35.768057 15072 W2lListFilesDataset.cpp:62] Total batches (i.e. iters): 25
I0902 19:30:35.776311 15077 W2lListFilesDataset.cpp:137] 2703 files found.
I0902 19:30:35.776397 15077 Utils.cpp:102] Filtered 0/2703 samples
I0902 19:30:35.776763 15077 W2lListFilesDataset.cpp:62] Total batches (i.e. iters): 25
I0902 19:30:35.827865 15071 W2lListFilesDataset.cpp:137] 2864 files found.
I0902 19:30:35.827961 15071 Utils.cpp:102] Filtered 0/2864 samples
I0902 19:30:35.828393 15071 W2lListFilesDataset.cpp:62] Total batches (i.e. iters): 26
I0902 19:30:36.064688 15075 W2lListFilesDataset.cpp:137] 2864 files found.
I0902 19:30:36.064771 15075 Utils.cpp:102] Filtered 0/2864 samples
I0902 19:30:36.065137 15075 W2lListFilesDataset.cpp:62] Total batches (i.e. iters): 26
I0902 19:30:36.072535 15074 W2lListFilesDataset.cpp:137] 2864 files found.
I0902 19:30:36.072618 15074 Utils.cpp:102] Filtered 0/2864 samples
I0902 19:30:36.073040 15074 W2lListFilesDataset.cpp:62] Total batches (i.e. iters): 26
I0902 19:30:36.092159 15076 W2lListFilesDataset.cpp:137] 2864 files found.
I0902 19:30:36.092239 15076 Utils.cpp:102] Filtered 0/2864 samples
I0902 19:30:36.092602 15076 W2lListFilesDataset.cpp:62] Total batches (i.e. iters): 26
I0902 19:30:36.095892 15072 W2lListFilesDataset.cpp:137] 2864 files found.
I0902 19:30:36.095983 15072 Utils.cpp:102] Filtered 0/2864 samples
I0902 19:30:36.096370 15072 W2lListFilesDataset.cpp:62] Total batches (i.e. iters): 26
I0902 19:30:36.100832 15073 W2lListFilesDataset.cpp:137] 2864 files found.
I0902 19:30:36.100908 15073 Utils.cpp:102] Filtered 0/2864 samples
I0902 19:30:36.101279 15073 W2lListFilesDataset.cpp:62] Total batches (i.e. iters): 26
I0902 19:30:36.102118 15077 W2lListFilesDataset.cpp:137] 2864 files found.
I0902 19:30:36.102185 15077 Utils.cpp:102] Filtered 0/2864 samples
I0902 19:30:36.102571 15077 W2lListFilesDataset.cpp:62] Total batches (i.e. iters): 26
I0902 19:30:36.239034 15071 Train.cpp:510] Shuffling trainset
I0902 19:30:36.488195 15071 Train.cpp:517] Epoch 1 started!
^[[AI0902 19:53:01.221380 15071 Train.cpp:313] epoch:        1 | lr: 0.050000 | lrcriterion: 0.050000 | runtime: 00:21:38 | bch(ms): 516.77 | smp(ms): 3.57 | fwd(ms): 158.14 | crit-fwd(ms): 35.16 | bwd(ms): 330.98 | optim(ms): 12.77 | loss:  615.81497 | train-LER: 105.51 | train-WER: 158.51 | dev-clean-loss:  634.13607 | dev-clean-LER: 223.01 | dev-clean-WER: 335.63 | dev-other-loss:  562.22262 | dev-other-LER: 258.55 | dev-other-WER: 379.26 | avg-isz: 1230 | avg-tsz: 135 | max-tsz: 311 | hrs:  961.27 | thrpt(sec/sec): 2665.84
I0902 19:53:03.235296 15071 Train.cpp:510] Shuffling trainset
I0902 19:53:03.236084 15071 Train.cpp:517] Epoch 2 started!
dI0902 20:15:07.098100 15071 Train.cpp:313] epoch:        2 | lr: 0.050000 | lrcriterion: 0.050000 | runtime: 00:21:19 | bch(ms): 509.46 | smp(ms): 3.73 | fwd(ms): 152.04 | crit-fwd(ms): 33.29 | bwd(ms): 329.98 | optim(ms): 12.87 | loss:  485.99588 | train-LER: 100.81 | train-WER: 151.21 | dev-clean-loss:  226.99981 | dev-clean-LER: 146.47 | dev-clean-WER: 217.68 | dev-other-loss:  198.67968 | dev-other-LER: 164.50 | dev-other-WER: 243.49 | avg-isz: 1230 | avg-tsz: 135 | max-tsz: 311 | hrs:  961.27 | thrpt(sec/sec): 2704.09
I0902 20:15:09.379187 15071 Train.cpp:510] Shuffling trainset
I0902 20:15:09.380385 15071 Train.cpp:517] Epoch 3 started!
I0902 20:37:19.932729 15071 Train.cpp:313] epoch:        3 | lr: 0.050000 | lrcriterion: 0.050000 | runtime: 00:21:26 | bch(ms): 512.16 | smp(ms): 3.97 | fwd(ms): 156.40 | crit-fwd(ms): 34.08 | bwd(ms): 329.03 | optim(ms): 12.73 | loss:  433.16234 | train-LER: 100.85 | train-WER: 146.45 | dev-clean-loss:  191.95757 | dev-clean-LER: 148.62 | dev-clean-WER: 217.79 | dev-other-loss:  170.87893 | dev-other-LER: 167.71 | dev-other-WER: 245.11 | avg-isz: 1230 | avg-tsz: 135 | max-tsz: 311 | hrs:  961.27 | thrpt(sec/sec): 2689.82
I0902 20:37:20.170555 15071 Train.cpp:510] Shuffling trainset
I0902 20:37:20.312649 15071 Train.cpp:517] Epoch 4 started!
I0902 20:59:13.587867 15071 Train.cpp:313] epoch:        4 | lr: 0.050000 | lrcriterion: 0.050000 | runtime: 00:21:19 | bch(ms): 509.27 | smp(ms): 3.62 | fwd(ms): 158.55 | crit-fwd(ms): 33.32 | bwd(ms): 324.76 | optim(ms): 12.74 | loss:  371.87434 | train-LER: 72.80 | train-WER: 101.77 | dev-clean-loss:  112.58519 | dev-clean-LER: 67.42 | dev-clean-WER: 104.99 | dev-other-loss:  112.08074 | dev-other-LER: 73.38 | dev-other-WER: 117.39 | avg-isz: 1230 | avg-tsz: 135 | max-tsz: 311 | hrs:  961.27 | thrpt(sec/sec): 2705.11
I0902 20:59:15.091936 15071 Train.cpp:510] Shuffling trainset
I0902 20:59:15.093612 15071 Train.cpp:517] Epoch 5 started!
I0902 21:20:54.381829 15071 Train.cpp:313] epoch:        5 | lr: 0.050000 | lrcriterion: 0.050000 | runtime: 00:21:09 | bch(ms): 505.33 | smp(ms): 3.72 | fwd(ms): 156.40 | crit-fwd(ms): 33.57 | bwd(ms): 323.38 | optim(ms): 12.76 | loss:  258.26638 | train-LER: 58.66 | train-WER: 83.67 | dev-clean-loss:   63.85422 | dev-clean-LER: 40.91 | dev-clean-WER: 66.03 | dev-other-loss:   76.63932 | dev-other-LER: 51.80 | dev-other-WER: 83.45 | avg-isz: 1230 | avg-tsz: 135 | max-tsz: 310 | hrs:  961.27 | thrpt(sec/sec): 2726.17
I0902 21:20:55.879005 15071 Train.cpp:510] Shuffling trainset
I0902 21:20:55.881127 15071 Train.cpp:517] Epoch 6 started!
I0902 21:42:35.163261 15071 Train.cpp:313] epoch:        6 | lr: 0.050000 | lrcriterion: 0.050000 | runtime: 00:21:10 | bch(ms): 505.87 | smp(ms): 3.76 | fwd(ms): 155.93 | crit-fwd(ms): 33.14 | bwd(ms): 324.66 | optim(ms): 12.85 | loss:  208.11860 | train-LER: 47.78 | train-WER: 69.51 | dev-clean-loss:   47.14540 | dev-clean-LER: 30.43 | dev-clean-WER: 50.79 | dev-other-loss:   60.66026 | dev-other-LER: 39.47 | dev-other-WER: 66.29 | avg-isz: 1230 | avg-tsz: 135 | max-tsz: 311 | hrs:  961.27 | thrpt(sec/sec): 2723.27
I0902 21:42:36.657009 15071 Train.cpp:510] Shuffling trainset
I0902 21:42:36.658643 15071 Train.cpp:517] Epoch 7 started!
I0902 22:04:23.755532 15071 Train.cpp:313] epoch:        7 | lr: 0.050000 | lrcriterion: 0.050000 | runtime: 00:21:18 | bch(ms): 509.12 | smp(ms): 4.00 | fwd(ms): 161.80 | crit-fwd(ms): 33.53 | bwd(ms): 322.06 | optim(ms): 12.81 | loss:  183.59331 | train-LER: 44.81 | train-WER: 65.46 | dev-clean-loss:   39.66723 | dev-clean-LER: 23.87 | dev-clean-WER: 39.57 | dev-other-loss:   54.54744 | dev-other-LER: 32.17 | dev-other-WER: 54.44 | avg-isz: 1230 | avg-tsz: 135 | max-tsz: 311 | hrs:  961.27 | thrpt(sec/sec): 2705.88
I0902 22:04:25.708479 15071 Train.cpp:510] Shuffling trainset
I0902 22:04:25.709515 15071 Train.cpp:517] Epoch 8 started!
I0902 22:26:09.314406 15071 Train.cpp:313] epoch:        8 | lr: 0.050000 | lrcriterion: 0.050000 | runtime: 00:21:15 | bch(ms): 507.85 | smp(ms): 3.86 | fwd(ms): 155.41 | crit-fwd(ms): 31.90 | bwd(ms): 327.28 | optim(ms): 12.72 | loss:  168.88211 | train-LER: 39.58 | train-WER: 57.22 | dev-clean-loss:   33.93754 | dev-clean-LER: 22.04 | dev-clean-WER: 35.86 | dev-other-loss:   48.57212 | dev-other-LER: 30.37 | dev-other-WER: 52.02 | avg-isz: 1230 | avg-tsz: 135 | max-tsz: 310 | hrs:  961.27 | thrpt(sec/sec): 2712.67
I0902 22:26:11.696326 15071 Train.cpp:510] Shuffling trainset
I0902 22:26:11.697422 15071 Train.cpp:517] Epoch 9 started!
I0902 22:48:07.109421 15071 Train.cpp:313] epoch:        9 | lr: 0.050000 | lrcriterion: 0.050000 | runtime: 00:21:28 | bch(ms): 512.82 | smp(ms): 3.78 | fwd(ms): 160.56 | crit-fwd(ms): 33.23 | bwd(ms): 327.08 | optim(ms): 12.69 | loss:  159.09930 | train-LER: 35.76 | train-WER: 51.45 | dev-clean-loss:   28.61177 | dev-clean-LER: 19.84 | dev-clean-WER: 32.08 | dev-other-loss:   42.29648 | dev-other-LER: 26.57 | dev-other-WER: 45.46 | avg-isz: 1230 | avg-tsz: 135 | max-tsz: 311 | hrs:  961.27 | thrpt(sec/sec): 2686.37
I0902 22:48:09.140770 15071 Train.cpp:510] Shuffling trainset
I0902 22:48:09.141738 15071 Train.cpp:517] Epoch 10 started!
I0902 23:09:49.112495 15071 Train.cpp:313] epoch:       10 | lr: 0.050000 | lrcriterion: 0.050000 | runtime: 00:21:12 | bch(ms): 506.74 | smp(ms): 3.60 | fwd(ms): 158.23 | crit-fwd(ms): 31.79 | bwd(ms): 323.01 | optim(ms): 12.78 | loss:  151.91839 | train-LER: 34.08 | train-WER: 48.48 | dev-clean-loss:   27.51201 | dev-clean-LER: 18.59 | dev-clean-WER: 29.36 | dev-other-loss:   43.20520 | dev-other-LER: 24.96 | dev-other-WER: 43.18 | avg-isz: 1230 | avg-tsz: 135 | max-tsz: 310 | hrs:  961.27 | thrpt(sec/sec): 2718.61
I0902 23:09:50.829989 15071 Train.cpp:510] Shuffling trainset
I0902 23:09:50.830945 15071 Train.cpp:517] Epoch 11 started!
```

I have all dependencies installed (flashlight distributed, MPI, ArrayFire, NCCL, MKL, FFTW3, etc.) as described in installation.md. Actually, the previous 19 minute figure was before I installed MKL (I had only OpenBLAS at the time); it is now actually over 21 minutes now that I have MKL. It could be that there is some discrepancy in the training script (as described in my issue #395 and the related #392 )?

**Comment by tlikhomanenko** [comment] 2019-09-04 19:44
hi @nimz,

I sent the fix of the lexicon file generation cfbd32cad980af9a90bb7494da08a79588b39a9b. The order of spellings matters for the training because of the way how we sample segmentation of the words and the segmentation length affects the training time. Could you rerun `prepare.py` again (or use the lexicon from the link in the README.md) and then run the training again?

**Comment by tlikhomanenko** [comment] 2019-09-15 09:37
Time problem is solved with fixed lexicon as reported in https://github.com/facebookresearch/wav2letter/issues/392. 

@nimz, does the problem with training on 8 GPUs still remain? I cannot reproduce the error. Can you test in simple case that `mpirun -n 8 ...` is working for you, so the problem is not with GPUs?

**Comment by WeiLi233** [comment] 2020-03-25 14:42
same problem, crash after some epochs, the log is:
[bless_log.log](https://github.com/facebookresearch/wav2letter/files/4381564/bless_log.log)

NVIDIA-SMI 410.78       Driver Version: 410.78       CUDA Version: 10.1

**Comment by WeiLi233** [comment] 2020-03-30 02:30
I think I found the reason why distribution training may failed... it was caused by not wav2letter but the mpirun mechanism, running mpirun with nohup and & is useless and may cause w2l training crash, replacing nohup + & by screen command solves this issue.

**Comment by tlikhomanenko** [comment] 2020-04-05 06:16
@WeiLi233, 

Thanks a lot for debugging and reporting solution!
Closing for now, feel free to chat if any other problems exist.

**Closed by tlikhomanenko** 2020-04-05 06:16 UTC
