### ISSUE TITLE
Running Pre-trained model using lexfree

### ISSUE THREAD

**Issue by adarsh123456789** [facebookresearch/wav2letter#437] opened 2019-10-31 06:27 UTC
Error message:
**root@cfd937d83256:~# wav2letter/build/Decoder --flagsfile /root/wav2letter/recipes/models/lexicon_free/librispeech/decoder_word_4gram_clean.cfg --minloglevel=0 --logtostderr=1
I1031 06:01:00.331007    12 Decode.cpp:57] Reading flags from file /root/wav2letter/recipes/models/lexicon_free/librispeech/decoder_word_4gram_clean.cfg
I1031 06:01:00.336213    12 Decode.cpp:85] [Network] Reading acoustic model from $MODEL_DST/am/baseline_dev-clean+other.bin
E1031 06:01:03.086669    12 Serial.h:74] Error while loading: failed to open file for reading
E1031 06:01:04.086935    12 Serial.h:74] Error while loading: failed to open file for reading
E1031 06:01:06.087193    12 Serial.h:74] Error while loading: failed to open file for reading
E1031 06:01:10.087438    12 Serial.h:74] Error while loading: failed to open file for reading
E1031 06:01:18.087675    12 Serial.h:74] Error while loading: failed to open file for reading
E1031 06:01:34.087920    12 Serial.h:74] Error while loading: failed to open file for reading
terminate called after throwing an instance of 'std::runtime_error'
  what():  failed to open file for reading
*** Aborted at 1572501694 (unix time) try "date -d @1572501694" if you are using GNU date ***
PC: @     0x7f83ff438428 gsignal
*** SIGABRT (@0xc) received by PID 12 (TID 0x7f84496a9600) from PID 12; stack trace: ***
    @     0x7f84419af390 (unknown)
    @     0x7f83ff438428 gsignal
    @     0x7f83ff43a02a abort
    @     0x7f83ffd7b84d __gnu_cxx::__verbose_terminate_handler()
    @     0x7f83ffd796b6 (unknown)
    @     0x7f83ffd79701 std::terminate()
    @     0x7f83ffd79969 __cxa_rethrow
    @           0x48b5b8 w2l::retryWithBackoff<>()
    @           0x418c80 main
    @     0x7f83ff423830 __libc_start_main
    @           0x47b7f9 _start
    @                0x0 (unknown)
Aborted (core dumped)**

Hi I am learning and trying to run the pre-trained model by referring:
[https://github.com/facebookresearch/wav2letter/tree/master/recipes/models/lexicon_free/librispeech]
Spinned the container using: 
`sudo docker run --runtime=nvidia -itd --ipc=host --name lexfree wav2letter/wav2letter:lexfree
sudo docker exec -it lexfree bash`

used the below commands to prepare data:
`cd wav2letter/recipes/models/lexicon_free/librispeech
python3 prepare.py --data_dst /root/wav2letter/data --model_dst /root/wav2letter/model --kenlm /root/wav2letter/kenlm
export MODEL_DST=/root/wav2letter/model
export DATA_DST=/root/wav2letter/data
mkdir $MODEL_DST/decoder/ngram_models $MODEL_DST/decoder/convlm_models
cd $MODEL_DST/decoder/ngram_models
wget https://dl.fbaipublicfiles.com/wav2letter/lexicon_free/librispeech/models/lm/lm_librispeech_kenlm_word_4g_200kvocab.bin

cd $MODEL_DST/am
wget https://dl.fbaipublicfiles.com/wav2letter/lexicon_free/librispeech/models/am/baseline_dev-clean%2Bother.bin`

`cd wav2letter/recipes/models/lexicon_free/librispeech
vi decoder_word_4gram_clean.cfg`

below is the configuration file:
**--am=$MODEL_DST/am/baseline_dev-clean+other.bin
--tokensdir=$MODEL_DST/am
--tokens=tokens.lst
--lexicon=$MODEL_DST/decoder/lexicon.lst
--lm=MODEL_DST/decoder/ngram_models/lm_librispeech_kenlm_word_4g_200kvocab.bin
--datadir=$DATA_DST/lists/
--test=test-clean.lst
--sclite=/root/wav2letter/sclite
--lmweight=3.5421582546219748
--wordscore=0.21285288398305346
--beamsize=8000
--beamthreshold=100
--silweight=-0.7691148206121685
--nthread_decoder=8
--smearing=max
--show=true
--showletters=true**

and then for decoding used the below code:
`wav2letter/build/Decoder --flagsfile /root/wav2letter/recipes/models/lexicon_free/librispeech/decoder_word_4gram_clean.cfg --minloglevel=0 --logtostderr=1`

using currently cuda 9.2

**Comment by tlikhomanenko** [comment] 2019-10-31 20:50
Hi @adarsh123456789,

The problem is in your config file. 
Unfortunatelly, we don't support `$VAR` usage inside config files, so you need to specify the full path to the models and files inside config file. For example, you should change `--am=$MODEL_DST/am/baseline_dev-clean+other.bin` to `--am=/root/wav2letter/model/am/baseline_dev-clean+other.bin` and so on for other paths where you are using `$...`.

**Comment by adarsh123456789** [comment] 2019-11-03 16:36
Thanks @tlikhomanenko 
Your solution did really solved the issue. There is one small doubt, I am not very sure, but I am still not able to understand how is the .wav file being used as input. What I found is, it is using .bin & .arpa files but I'm not able to understand where and how is the conversion happening? 

P.S. Might be a very lame doubt, but i'm new to this so, please help! 
Thanks in advance

**Comment by tlikhomanenko** [comment] 2019-11-04 14:10
Hi @adarsh123456789, 

Here is https://github.com/facebookresearch/wav2letter/blob/master/Decode.cpp#L151 dataset is created (where the file with list of wav files and original transcriptions is used). 

Precisely: list file is read here https://github.com/facebookresearch/wav2letter/blob/master/src/data/W2lListFilesDataset.cpp#L101, and wav files are read on fly when we are iterating over dataset https://github.com/facebookresearch/wav2letter/blob/master/Decode.cpp#L157 with function https://github.com/facebookresearch/wav2letter/blob/master/src/data/W2lListFilesDataset.cpp#L81.

Hope, this will help you.

Closing issue for now, feel free to reopen/create new issue if it is necessary!

**Closed by tlikhomanenko** 2019-11-04 14:10 UTC
