### ISSUE TITLE
Pre-trained models, CPU-only

### ISSUE THREAD

**Issue by JanX2** [facebookresearch/wav2letter#6] opened 2018-01-03 10:39 UTC
After a few smaller patches (forthcoming) I got through the whole process describe in the README for testing the pre-trained models. Up to the point where I can finally run `test.lua`. I’m pretty confident that this would run, but I can’t get `test.lua` to run CPU-only. I don’t have an nVidia card handy and so didn’t install any CUDA-related libraries.

So I’m running `test.lua` with `-gpu 0` (which requires another forthcoming patch) and this is where I’m stuck: 

```
| number of classes (network) = 30
| reloading model </Volumes/Rest/Temp/prem 201X-XX-XX/LibriSpeech-11/librispeech-glu-highdropout.bin>
luajit: ...ment/Projects/torch/install/share/lua/5.1/torch/File.lua:343: unknown Torch class <torch.CudaTensor>
stack traceback:
	[C]: in function 'error'
	...ment/Projects/torch/install/share/lua/5.1/torch/File.lua:343: in function 'readObject'
	...ment/Projects/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	...pment/Projects/torch/install/share/lua/5.1/nn/Module.lua:192: in function 'read'
	...ment/Projects/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	...ment/Projects/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	...ment/Projects/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	...pment/Projects/torch/install/share/lua/5.1/nn/Module.lua:192: in function 'read'
	...ment/Projects/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	...ment/Projects/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	...orch/install/share/lua/5.1/wav2letter/runtime/serial.lua:57: in function 'loadmodel'
	...do/Development/Projects/wav2letter-Facebook-STT/test.lua:108: in main chunk
	[C]: at 0x010319be60
```

The issue appears to be similar to <https://github.com/soumith/dcgan.torch/issues/28>, but I don’t know enough of the architecture to make progress here quick. 

It looks like the network was saved in GPU-only mode and requires some kind of conversion to run CPU-only. Is this correct?

In that case, an you supply a CPU-only or hybrid model?

Thanks for all the work you put into this project!

**Comment by JanX2** [comment] 2018-01-03 10:59
PR #5 has my small patches.

**Comment by VitaliyLi** [comment] 2018-01-03 18:43
Hi, yes, we are working on converting our GPU model and supplying CPU-only model.

**Comment by JanX2** [comment] 2018-01-09 12:44
That should have been PR #7.

**Comment by soswow** [comment] 2018-01-10 21:25
Duplicate of #4 but I like that this one is still open

**Comment by VitaliyLi** [comment] 2018-01-11 06:29
CPU model has been uploaded:
https://s3.amazonaws.com/wav2letter/models/librispeech-glu-highdropout-cpu.bin

**Closed by VitaliyLi** 2018-01-11 06:29 UTC
