### ISSUE TITLE
Compilation Error: "expected primary-expression before ‘)’ token"

### ISSUE THREAD

**Issue by syb0rg** [facebookresearch/wav2letter#94] opened 2018-12-22 00:36 UTC
Trace of error shown below, all previous installation steps were accomplished successfully.

```
~/Downloads/wav2letter/build$ make
[  1%] Built target warpctc
[  2%] Building CXX object CMakeFiles/wav2letter++.dir/src/criterion/Seq2SeqCriterion.cpp.o
In file included from /usr/local/include/flashlight/autograd/Variable.h:24:0,
                 from /usr/local/include/flashlight/autograd/autograd.h:19,
                 from /usr/local/include/flashlight/flashlight.h:10,
                 from ~/Downloads/wav2letter/src/criterion/SequenceCriterion.h:11,
                 from ~/Downloads/wav2letter/src/criterion/Seq2SeqCriterion.h:12,
                 from ~/Downloads/wav2letter/src/criterion/Seq2SeqCriterion.cpp:9:
~/Downloads/wav2letter/src/criterion/attention/WindowBase.h: In member function ‘void fl::WindowBase::save(Archive&, uint32_t) const’:
~/Downloads/wav2letter/src/criterion/attention/WindowBase.h:31:3: error: expected primary-expression before ‘)’ token
   FL_SAVE_LOAD()
```

**Comment by jacobkahn** [comment] 2018-12-22 02:50
Thanks for reporting @syb0rg - what's your OS/compiler version so we can reproduce?

**Comment by nhynes** [comment] 2018-12-22 07:02
I'm also getting this error (building off of master gives similar errors).

Specs:

```
$ g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609

$ cmake --version
cmake version 3.5.1  # because cmake 3.10.2 doesn't have `find_dependency`
```

building off of flashlight v0.1

**Comment by nhynes** [comment] 2018-12-22 07:15
The issue seems to be with the [`##__VA_ARGS__` in `FL_SAVE_LOAD`](https://github.com/facebookresearch/flashlight/blob/master/flashlight/common/Serialization.h#L84). In particular that there's an dangling comma when there are no varargs.

Applying the following patch builds just fine

```diff
diff --git a/src/criterion/attention/WindowBase.h b/src/criterion/attention/WindowBase.h
index a601b0d..e4209f1 100644
--- a/src/criterion/attention/WindowBase.h
+++ b/src/criterion/attention/WindowBase.h
@@ -28,7 +28,8 @@ class WindowBase {
   virtual ~WindowBase() {}

  private:
-  FL_SAVE_LOAD()
+  int _the;
+  FL_SAVE_LOAD(_the)
 };

 } // namespace fl
```

**Comment by vineelpratap** [comment] 2018-12-22 07:51
We are able to repro the issue and we should have the fix committed to the repo soon. Till then, the above the patch should work as a quick-fix. 

Thanks !

**Comment by jacobkahn** [comment] 2018-12-22 07:53
120f78e551d8197df94630aeb0c5c2f040ccf1a9 stops disabling `gnu++11` compiler additions were disabled with the build, which are necessary to expand `## __VA_ARGS__`. This should fix the issue for now on Linux-based systems.

**Closed** 2018-12-22 08:20 UTC
Labels: bug
