### ISSUE TITLE
Build fail with CMAKE_BUILD_TYPE=Release

### ISSUE THREAD

**Issue by yutkin** [facebookresearch/wav2letter#417] opened 2019-10-05 10:14 UTC
Building with `-D CMAKE_BUILD_TYPE=Release` fails:
```
RUN git clone --recursive https://github.com/facebookresearch/wav2letter.git && \
    cd wav2letter \
    && mkdir build && cd build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release -DW2L_LIBRARIES_USE_CUDA=ON -DW2L_BUILD_TESTS=OFF -DW2L_BUILD_EXAMPLES=OFF && \
    make -j $BUILD_JOBS
```
```
CMakeFiles/Decoder.dir/src/data/W2lBlobsDataset.cpp.o: In function `w2l::W2lBlobsDataset::getLoaderData(long) const':
W2lBlobsDataset.cpp:(.text+0x2399): undefined reference to `std::vector<float, std::allocator<float> > w2l::loadSound<float>(std::istream&)'
collect2: error: ld returned 1 exit status
CMakeFiles/Decoder.dir/build.make:1103: recipe for target 'Decoder' failed
make[2]: *** [Decoder] Error 1
CMakeFiles/Makefile2:192: recipe for target 'CMakeFiles/Decoder.dir/all' failed
make[1]: *** [CMakeFiles/Decoder.dir/all] Error 2

[100%] Linking CXX executable SerializeConvLM
CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/data/W2lBlobsDataset.cpp.o: In function `w2l::W2lBlobsDataset::getLoaderData(long) const':
W2lBlobsDataset.cpp:(.text+0x2399): undefined reference to `std::vector<float, std::allocator<float> > w2l::loadSound<float>(std::istream&)'
collect2: error: ld returned 1 exit status
make[2]: *** [recipes/models/utilities/convlm_serializer/SerializeConvLM] Error 1
recipes/models/utilities/convlm_serializer/CMakeFiles/SerializeConvLM.dir/build.make:1119: recipe for target 'recipes/models/utilities/convlm_serializer/SerializeConvLM' failed
CMakeFiles/Makefile2:623: recipe for target 'recipes/models/utilities/convlm_serializer/CMakeFiles/SerializeConvLM.dir/all' failed
make[1]: *** [recipes/models/utilities/convlm_serializer/CMakeFiles/SerializeConvLM.dir/all] Error 2
make: *** [all] Error 2
Makefile:129: recipe for target 'all' failed
```

Full build log on [gist](https://gist.github.com/yutkin/b8594ae4678aa878698c5673fadd2145).

Full [Dockerfile](https://gist.github.com/yutkin/ce9ffb3a7f8fd76a2fd30676ecdd2ce3).

Without `-DCMAKE_BUILD_TYPE=Release` (i.e. in `Debug`) build pass successfully.

**Comment by lunixbochs** [comment] 2019-10-15 16:21
Dupes one of the unresolved issues in https://github.com/facebookresearch/wav2letter/issues/375

**Comment by jacobkahn** [comment] 2019-11-08 19:28
@yutkin — I've seen this issue occasionally as well. It's been frustrating to repro. Can you tell me everything you can about your platform? Are you able to build with our Dockerfile in release mode on that same platform? I'm pretty sure it's related to how `extern` is working on some of the libsndfile stuff.

**Comment by jacobkahn** [comment] 2019-12-03 19:28
Fixed in 4289710cd65f03722d6d0d20d801e82290823408!

**Closed by jacobkahn** 2019-12-03 19:28 UTC

**Comment by rajpuneet** [comment] 2020-02-17 22:22
I am still facing the same issue.

```
mkdir -p build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
make -j4
```

```
CMakeFiles/RuntimeTest.dir/__/criterion/ConnectionistTemporalClassificationCriterion.cpp.o: In function `w2l::ConnectionistTemporalClassificationCriterion::viterbiPath(af::array const&, af::array const&)':
ConnectionistTemporalClassificationCriterion.cpp:(.text+0x126d): undefined reference to `w2l::cpu::ConnectionistTemporalClassificationCriterion<float>::getWorkspaceSize(int, int, int, int)'
ConnectionistTemporalClassificationCriterion.cpp:(.text+0x131d): undefined reference to `w2l::cpu::ConnectionistTemporalClassificationCriterion<float>::viterbi(int, int, int, int, float const*, int const*, int const*, int*, void*)'
CMakeFiles/RuntimeTest.dir/__/runtime/Logger.cpp.o: In function `w2l::getStatus(w2l::TrainMeters&, long, double, double, bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
Logger.cpp:(.text+0x2b8f): undefined reference to `fl::getWorldSize()'
CMakeFiles/RuntimeTest.dir/__/runtime/Logger.cpp.o: In function `w2l::allreduceSet(fl::TimeMeter&, af::array&)':
Logger.cpp:(.text+0x375f): undefined reference to `fl::getWorldSize()'
CMakeFiles/RuntimeTest.dir/__/runtime/Logger.cpp.o: In function `void w2l::syncMeter<w2l::TrainMeters>(w2l::TrainMeters&)':
Logger.cpp:(.text+0x37fc): undefined reference to `fl::isDistributedInit()'
Logger.cpp:(.text+0x385f): undefined reference to `fl::isDistributedInit()'
Logger.cpp:(.text+0x38a3): undefined reference to `fl::isDistributedInit()'
Logger.cpp:(.text+0x38c3): undefined reference to `fl::allReduce(af::array&, bool)'
Logger.cpp:(.text+0x392b): undefined reference to `fl::allReduce(af::array&, bool)'
Logger.cpp:(.text+0x396b): undefined reference to `fl::allReduce(af::array&, bool)'
CMakeFiles/RuntimeTest.dir/__/runtime/Logger.cpp.o: In function `void w2l::syncMeter<fl::TimeMeter>(fl::TimeMeter&)':
Logger.cpp:(.text._ZN3w2l9syncMeterIN2fl9TimeMeterEEEvRT_[_ZN3w2l9syncMeterIN2fl9TimeMeterEEEvRT_]+0x19): undefined reference to `fl::isDistributedInit()'
Logger.cpp:(.text._ZN3w2l9syncMeterIN2fl9TimeMeterEEEvRT_[_ZN3w2l9syncMeterIN2fl9TimeMeterEEEvRT_]+0x60): undefined reference to `fl::allReduce(af::array&, bool)'
CMakeFiles/RuntimeTest.dir/__/runtime/Logger.cpp.o: In function `void w2l::syncMeter<fl::EditDistanceMeter>(fl::EditDistanceMeter&)':
Logger.cpp:(.text._ZN3w2l9syncMeterIN2fl17EditDistanceMeterEEEvRT_[_ZN3w2l9syncMeterIN2fl17EditDistanceMeterEEEvRT_]+0x19): undefined reference to `fl::isDistributedInit()'
Logger.cpp:(.text._ZN3w2l9syncMeterIN2fl17EditDistanceMeterEEEvRT_[_ZN3w2l9syncMeterIN2fl17EditDistanceMeterEEEvRT_]+0x51): undefined reference to `fl::allReduce(af::array&, bool)'
CMakeFiles/RuntimeTest.dir/__/runtime/Distributed.cpp.o: In function `w2l::initDistributed(int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
Distributed.cpp:(.text+0x312): undefined reference to `fl::distributedInit(fl::DistributedInit, int, int, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)'
Distributed.cpp:(.text+0x611): undefined reference to `fl::distributedInit(fl::DistributedInit, int, int, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)'
collect2: error: ld returned 1 exit status
src/tests/CMakeFiles/RuntimeTest.dir/build.make:1099: recipe for target 'src/tests/RuntimeTest' failed
make[2]: *** [src/tests/RuntimeTest] Error 1
CMakeFiles/Makefile2:665: recipe for target 'src/tests/CMakeFiles/RuntimeTest.dir/all' failed
make[1]: *** [src/tests/CMakeFiles/RuntimeTest.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 22%] [32mBuilding CXX object CMakeFiles/Train.dir/src/runtime/Helpers.cpp.o[0m
[ 23%] [32m[1mLinking CXX executable Decoder[0m
[ 23%] [32m[1mLinking CXX executable Test[0m
CMakeFiles/Decoder.dir/src/criterion/ConnectionistTemporalClassificationCriterion.cpp.o: In function `w2l::ConnectionistTemporalClassificationCriterion::viterbiPath(af::array const&, af::array const&)':
ConnectionistTemporalClassificationCriterion.cpp:(.text+0x126d): undefined reference to `w2l::cpu::ConnectionistTemporalClassificationCriterion<float>::getWorkspaceSize(int, int, int, int)'
ConnectionistTemporalClassificationCriterion.cpp:(.text+0x131d): undefined reference to `w2l::cpu::ConnectionistTemporalClassificationCriterion<float>::viterbi(int, int, int, int, float const*, int const*, int const*, int*, void*)'
CMakeFiles/Decoder.dir/src/runtime/Logger.cpp.o: In function `w2l::getStatus(w2l::TrainMeters&, long, double, double, bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
Logger.cpp:(.text+0x2b8f): undefined reference to `fl::getWorldSize()'
CMakeFiles/Decoder.dir/src/runtime/Logger.cpp.o: In function `w2l::allreduceSet(fl::TimeMeter&, af::array&)':
Logger.cpp:(.text+0x375f): undefined reference to `fl::getWorldSize()'
CMakeFiles/Decoder.dir/src/runtime/Logger.cpp.o: In function `void w2l::syncMeter<w2l::TrainMeters>(w2l::TrainMeters&)':
Logger.cpp:(.text+0x37fc): undefined reference to `fl::isDistributedInit()'
Logger.cpp:(.text+0x385f): undefined reference to `fl::isDistributedInit()'
Logger.cpp:(.text+0x38a3): undefined reference to `fl::isDistributedInit()'
Logger.cpp:(.text+0x38c3): undefined reference to `fl::allReduce(af::array&, bool)'
Logger.cpp:(.text+0x392b): undefined reference to `fl::allReduce(af::array&, bool)'
Logger.cpp:(.text+0x396b): undefined reference to `fl::allReduce(af::array&, bool)'
CMakeFiles/Decoder.dir/src/runtime/Logger.cpp.o: In function `void w2l::syncMeter<fl::TimeMeter>(fl::TimeMeter&)':
Logger.cpp:(.text._ZN3w2l9syncMeterIN2fl9TimeMeterEEEvRT_[_ZN3w2l9syncMeterIN2fl9TimeMeterEEEvRT_]+0x19): undefined reference to `fl::isDistributedInit()'
Logger.cpp:(.text._ZN3w2l9syncMeterIN2fl9TimeMeterEEEvRT_[_ZN3w2l9syncMeterIN2fl9TimeMeterEEEvRT_]+0x60): undefined reference to `fl::allReduce(af::array&, bool)'
CMakeFiles/Decoder.dir/src/runtime/Logger.cpp.o: In function `void w2l::syncMeter<fl::EditDistanceMeter>(fl::EditDistanceMeter&)':
Logger.cpp:(.text._ZN3w2l9syncMeterIN2fl17EditDistanceMeterEEEvRT_[_ZN3w2l9syncMeterIN2fl17EditDistanceMeterEEEvRT_]+0x19): undefined reference to `fl::isDistributedInit()'
Logger.cpp:(.text._ZN3w2l9syncMeterIN2fl17EditDistanceMeterEEEvRT_[_ZN3w2l9syncMeterIN2fl17EditDistanceMeterEEEvRT_]+0x51): undefined reference to `fl::allReduce(af::array&, bool)'
CMakeFiles/Decoder.dir/src/runtime/Distributed.cpp.o: In function `w2l::initDistributed(int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
Distributed.cpp:(.text+0x312): undefined reference to `fl::distributedInit(fl::DistributedInit, int, int, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)'
Distributed.cpp:(.text+0x611): undefined reference to `fl::distributedInit(fl::DistributedInit, int, int, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)'
collect2: error: ld returned 1 exit status
CMakeFiles/Decoder.dir/build.make:1095: recipe for target 'Decoder' failed
make[2]: *** [Decoder] Error 1
CMakeFiles/Makefile2:437: recipe for target 'CMakeFiles/Decoder.dir/all' failed
make[1]: *** [CMakeFiles/Decoder.dir/all] Error 2
CMakeFiles/Test.dir/src/criterion/ConnectionistTemporalClassificationCriterion.cpp.o: In function `w2l::ConnectionistTemporalClassificationCriterion::viterbiPath(af::array const&, af::array const&)':
ConnectionistTemporalClassificationCriterion.cpp:(.text+0x126d): undefined reference to `w2l::cpu::ConnectionistTemporalClassificationCriterion<float>::getWorkspaceSize(int, int, int, int)'
ConnectionistTemporalClassificationCriterion.cpp:(.text+0x131d): undefined reference to `w2l::cpu::ConnectionistTemporalClassificationCriterion<float>::viterbi(int, int, int, int, float const*, int const*, int const*, int*, void*)'
CMakeFiles/Test.dir/src/runtime/Logger.cpp.o: In function `w2l::getStatus(w2l::TrainMeters&, long, double, double, bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
Logger.cpp:(.text+0x2b8f): undefined reference to `fl::getWorldSize()'
CMakeFiles/Test.dir/src/runtime/Logger.cpp.o: In function `w2l::allreduceSet(fl::TimeMeter&, af::array&)':
Logger.cpp:(.text+0x375f): undefined reference to `fl::getWorldSize()'
CMakeFiles/Test.dir/src/runtime/Logger.cpp.o: In function `void w2l::syncMeter<w2l::TrainMeters>(w2l::TrainMeters&)':
Logger.cpp:(.text+0x37fc): undefined reference to `fl::isDistributedInit()'
Logger.cpp:(.text+0x385f): undefined reference to `fl::isDistributedInit()'
Logger.cpp:(.text+0x38a3): undefined reference to `fl::isDistributedInit()'
Logger.cpp:(.text+0x38c3): undefined reference to `fl::allReduce(af::array&, bool)'
Logger.cpp:(.text+0x392b): undefined reference to `fl::allReduce(af::array&, bool)'
Logger.cpp:(.text+0x396b): undefined reference to `fl::allReduce(af::array&, bool)'
CMakeFiles/Test.dir/src/runtime/Logger.cpp.o: In function `void w2l::syncMeter<fl::TimeMeter>(fl::TimeMeter&)':
Logger.cpp:(.text._ZN3w2l9syncMeterIN2fl9TimeMeterEEEvRT_[_ZN3w2l9syncMeterIN2fl9TimeMeterEEEvRT_]+0x19): undefined reference to `fl::isDistributedInit()'
Logger.cpp:(.text._ZN3w2l9syncMeterIN2fl9TimeMeterEEEvRT_[_ZN3w2l9syncMeterIN2fl9TimeMeterEEEvRT_]+0x60): undefined reference to `fl::allReduce(af::array&, bool)'
CMakeFiles/Test.dir/src/runtime/Logger.cpp.o: In function `void w2l::syncMeter<fl::EditDistanceMeter>(fl::EditDistanceMeter&)':
Logger.cpp:(.text._ZN3w2l9syncMeterIN2fl17EditDistanceMeterEEEvRT_[_ZN3w2l9syncMeterIN2fl17EditDistanceMeterEEEvRT_]+0x19): undefined reference to `fl::isDistributedInit()'
Logger.cpp:(.text._ZN3w2l9syncMeterIN2fl17EditDistanceMeterEEEvRT_[_ZN3w2l9syncMeterIN2fl17EditDistanceMeterEEEvRT_]+0x51): undefined reference to `fl::allReduce(af::array&, bool)'
CMakeFiles/Test.dir/src/runtime/Distributed.cpp.o: In function `w2l::initDistributed(int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
Distributed.cpp:(.text+0x312): undefined reference to `fl::distributedInit(fl::DistributedInit, int, int, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)'
Distributed.cpp:(.text+0x611): undefined reference to `fl::distributedInit(fl::DistributedInit, int, int, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)'
collect2: error: ld returned 1 exit status
CMakeFiles/Test.dir/build.make:1095: recipe for target 'Test' failed
make[2]: *** [Test] Error 1
CMakeFiles/Makefile2:467: recipe for target 'CMakeFiles/Test.dir/all' failed
make[1]: *** [CMakeFiles/Test.dir/all] Error 2
[ 23%] [32m[1mLinking CXX executable Train[0m
CMakeFiles/Train.dir/Train.cpp.o: In function `main::{lambda(std::shared_ptr<fl::Module>, std::shared_ptr<w2l::SequenceCriterion>, std::shared_ptr<w2l::W2lDataset>, std::shared_ptr<fl::FirstOrderOptimizer>, std::shared_ptr<fl::FirstOrderOptimizer>, double, double, bool, int)#5}::operator()(std::shared_ptr<fl::Module>, std::shared_ptr<w2l::SequenceCriterion>, std::shared_ptr<w2l::W2lDataset>, std::shared_ptr<fl::FirstOrderOptimizer>, std::shared_ptr<fl::FirstOrderOptimizer>, double, double, bool, int) const::{lambda(long, double, double)#2}::operator()(long, double, double) const':
Train.cpp:(.text+0x3df8): undefined reference to `fl::getWorldRank()'
CMakeFiles/Train.dir/Train.cpp.o: In function `main::{lambda(std::shared_ptr<fl::Module>, std::shared_ptr<w2l::SequenceCriterion>, std::shared_ptr<w2l::W2lDataset>, std::shared_ptr<fl::FirstOrderOptimizer>, std::shared_ptr<fl::FirstOrderOptimizer>, double, double, bool, int)#5}::operator()(std::shared_ptr<fl::Module>, std::shared_ptr<w2l::SequenceCriterion>, std::shared_ptr<w2l::W2lDataset>, std::shared_ptr<fl::FirstOrderOptimizer>, std::shared_ptr<fl::FirstOrderOptimizer>, double, double, bool, int) const [clone .constprop.12666]':
Train.cpp:(.text+0x49f1): undefined reference to `fl::distributeModuleGrads(std::shared_ptr<fl::Module const>, std::shared_ptr<fl::Reducer>)'
Train.cpp:(.text+0x4a47): undefined reference to `fl::distributeModuleGrads(std::shared_ptr<fl::Module const>, std::shared_ptr<fl::Reducer>)'
Train.cpp:(.text+0x4ad0): undefined reference to `fl::allReduceParameters(std::shared_ptr<fl::Module const>)'
Train.cpp:(.text+0x4aff): undefined reference to `fl::allReduceParameters(std::shared_ptr<fl::Module const>)'
Train.cpp:(.text+0x4c6d): undefined reference to `fl::getWorldRank()'
Train.cpp:(.text+0x4cce): undefined reference to `fl::getWorldRank()'
CMakeFiles/Train.dir/Train.cpp.o: In function `main':
Train.cpp:(.text.startup+0x48f): undefined reference to `fl::getWorldSize()'
Train.cpp:(.text.startup+0x4eb): undefined reference to `fl::CoalescingReducer::CoalescingReducer(double, bool, bool)'
Train.cpp:(.text.startup+0x51d): undefined reference to `fl::getWorldRank()'
Train.cpp:(.text.startup+0x52a): undefined reference to `fl::getWorldSize()'
Train.cpp:(.text.startup+0x53e): undefined reference to `fl::getWorldRank()'
Train.cpp:(.text.startup+0x54b): undefined reference to `fl::getWorldRank()'
Train.cpp:(.text.startup+0x558): undefined reference to `fl::getWorldRank()'
Train.cpp:(.text.startup+0x1d5b): undefined reference to `fl::getWorldRank()'
Train.cpp:(.text.startup+0x1e6e): undefined reference to `fl::getWorldRank()'
CMakeFiles/Train.dir/Train.cpp.o:Train.cpp:(.text.startup+0x1e7b): more undefined references to `fl::getWorldRank()' follow
CMakeFiles/Train.dir/src/criterion/ConnectionistTemporalClassificationCriterion.cpp.o: In function `w2l::ConnectionistTemporalClassificationCriterion::viterbiPath(af::array const&, af::array const&)':
ConnectionistTemporalClassificationCriterion.cpp:(.text+0x126d): undefined reference to `w2l::cpu::ConnectionistTemporalClassificationCriterion<float>::getWorkspaceSize(int, int, int, int)'
ConnectionistTemporalClassificationCriterion.cpp:(.text+0x131d): undefined reference to `w2l::cpu::ConnectionistTemporalClassificationCriterion<float>::viterbi(int, int, int, int, float const*, int const*, int const*, int*, void*)'
CMakeFiles/Train.dir/src/runtime/Logger.cpp.o: In function `w2l::getStatus(w2l::TrainMeters&, long, double, double, bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
Logger.cpp:(.text+0x2b8f): undefined reference to `fl::getWorldSize()'
CMakeFiles/Train.dir/src/runtime/Logger.cpp.o: In function `w2l::allreduceSet(fl::TimeMeter&, af::array&)':
Logger.cpp:(.text+0x375f): undefined reference to `fl::getWorldSize()'
CMakeFiles/Train.dir/src/runtime/Logger.cpp.o: In function `void w2l::syncMeter<w2l::TrainMeters>(w2l::TrainMeters&)':
Logger.cpp:(.text+0x37fc): undefined reference to `fl::isDistributedInit()'
Logger.cpp:(.text+0x385f): undefined reference to `fl::isDistributedInit()'
Logger.cpp:(.text+0x38a3): undefined reference to `fl::isDistributedInit()'
Logger.cpp:(.text+0x38c3): undefined reference to `fl::allReduce(af::array&, bool)'
Logger.cpp:(.text+0x392b): undefined reference to `fl::allReduce(af::array&, bool)'
Logger.cpp:(.text+0x396b): undefined reference to `fl::allReduce(af::array&, bool)'
CMakeFiles/Train.dir/src/runtime/Logger.cpp.o: In function `void w2l::syncMeter<fl::TimeMeter>(fl::TimeMeter&)':
Logger.cpp:(.text._ZN3w2l9syncMeterIN2fl9TimeMeterEEEvRT_[_ZN3w2l9syncMeterIN2fl9TimeMeterEEEvRT_]+0x19): undefined reference to `fl::isDistributedInit()'
Logger.cpp:(.text._ZN3w2l9syncMeterIN2fl9TimeMeterEEEvRT_[_ZN3w2l9syncMeterIN2fl9TimeMeterEEEvRT_]+0x60): undefined reference to `fl::allReduce(af::array&, bool)'
CMakeFiles/Train.dir/src/runtime/Logger.cpp.o: In function `void w2l::syncMeter<fl::EditDistanceMeter>(fl::EditDistanceMeter&)':
Logger.cpp:(.text._ZN3w2l9syncMeterIN2fl17EditDistanceMeterEEEvRT_[_ZN3w2l9syncMeterIN2fl17EditDistanceMeterEEEvRT_]+0x19): undefined reference to `fl::isDistributedInit()'
Logger.cpp:(.text._ZN3w2l9syncMeterIN2fl17EditDistanceMeterEEEvRT_[_ZN3w2l9syncMeterIN2fl17EditDistanceMeterEEEvRT_]+0x51): undefined reference to `fl::allReduce(af::array&, bool)'
CMakeFiles/Train.dir/src/runtime/Distributed.cpp.o: In function `w2l::initDistributed(int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
Distributed.cpp:(.text+0x312): undefined reference to `fl::distributedInit(fl::DistributedInit, int, int, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)'
Distributed.cpp:(.text+0x611): undefined reference to `fl::distributedInit(fl::DistributedInit, int, int, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)'
collect2: error: ld returned 1 exit status
CMakeFiles/Train.dir/build.make:1095: recipe for target 'Train' failed
make[2]: *** [Train] Error 1
CMakeFiles/Makefile2:497: recipe for target 'CMakeFiles/Train.dir/all' failed
make[1]: *** [CMakeFiles/Train.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by lunixbochs** [comment] 2020-02-17 22:59
Your issue is caused by something other than the one posted here. I'm assuming your flashlight isn't built with distributed mode, or you're on a mac.

**Comment by rajpuneet** [comment] 2020-02-18 01:16
I’m on a linux machine. You are right that my flashlight is not built with distributed mode because I’m gonna be training on a single machine with 2 GPUs. Am I wrong about that?

**Comment by lunixbochs** [comment] 2020-02-18 01:17
It still needs to be compiled with distributed mode to use wav2letter. Also distributed mode is required for two gpus anyway.
