### ISSUE TITLE
LibriSpeech example generated ArrayFire error

### ISSUE THREAD

**Issue by feliiiiicity** [facebookresearch/wav2letter#111] opened 2019-01-02 09:03 UTC
Hi, I've installed wav2letter in Ubuntu 16.04 system with CPU backend, when I followed the tutorial step:

[...]/wav2letter/build/Train train --flagsfile [...]/wav2letter/tutorials/librispeech_clean/train.cfg

the process failed immediately with error info:

terminate called after throwing an instance of 'af::exceotion'
    what(): ArrayFire Exception (Internal error:998):
In function af_err af_create_handle(void**, unsigned int, const dim_t*, af_dtype)
In file src/api/c/array.cpp:84

In function void af::initEmptyArray(void**, af::dtype, dim_t, dim_t, dim_t, dim_t)
In file src/api/cpp/array.cpp:131
Aborted (core dump)

Well I assume that ArrayFire has been successfully installed since I've tested the helloworld test as given in its github page. Any instruction for this problem? Thanks.

**Comment by jacobkahn** [comment] 2019-01-02 17:40
@feliiiiicity — I'm pretty sure this is actually the same issue as https://github.com/facebookresearch/wav2letter/issues/108, which is caused by ArrayFire being doubly linked on build. I'll send a fix today.

**Comment by jacobkahn** [comment] 2019-01-02 21:53
The fix is in 8c3ba52d103697a767f16e478e5ddcced14d4115 — this should resolve the issue. Feel free to reopen if you're still having trouble.

**Closed by jacobkahn** 2019-01-02 21:53 UTC
