### ISSUE TITLE
sysmalloc: Assertion failed (simple streaming ASR example)

### ISSUE THREAD

**Issue by tdeboissiere** [facebookresearch/wav2letter#489] opened 2020-01-21 12:38 UTC
Hi,

I just built wav2letter from source and I was trying to run the simple streaming ASR example.
Models, tokens, etc were loaded successfully, but I then got the following assertion error

```
 cat ~/audio/LibriSpeech/dev-clean/777/126732/777-126732-0070.flac.wav | inference/inference/examples/simple_streaming_asr_example --input_files_base_path ~/model
Started features model file loading ... 
Completed features model file loading elapsed time=29637 microseconds

Started acoustic model file loading ... 
Completed acoustic model file loading elapsed time=5294 milliseconds

Started tokens file loading ... 
Completed tokens file loading elapsed time=934 microseconds

Tokens loaded - 9998 tokens
Started decoder options file loading ... 
Completed decoder options file loading elapsed time=51 microseconds

Started create decoder ... 
[Letters] 9998 tokens loaded.
[Words] 200001 words loaded.
simple_streaming_asr_example: malloc.c:2401: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
[1]    25663 broken pipe          cat ~/audio/LibriSpeech/dev-clean/777/126732/777-126732-0070.flac.wav | 
       25664 abort (core dumped)  inference/inference/examples/simple_streaming_asr_example  ~/model
```

**Build details:**

Followed instructions from https://github.com/facebookresearch/wav2letter/wiki/General-building-instructions

Nvidia drivers: 440.33.01
MKL 2018
MKL-DNN from branch mnt-v0
OpenBLAS, ArrayFire, Flashlight, Wav2letter, KenLM built from their respective master
Ubuntu 18.04
CUDA 10.2
Cudnn 7.6.5
NCCL 2.5.6.1

Any clues ?

**Comment by avidov** [comment] 2020-01-21 15:37
I did not see this error before.
Please run in gdb and send me the stack trace. 

You can build the inference with fewer dependencies following https://github.com/facebookresearch/wav2letter/wiki/Inference-Run-Examples
I would try that and see is it gets you forward.

**Comment by mortont** [comment] 2020-01-21 16:46
I'm running into the same error using the same setup (just built everything from their respective master branches). I've attached my stack trace [here](https://github.com/facebookresearch/wav2letter/files/4092222/gdb-debug.log).

**Comment by tdeboissiere** [comment] 2020-01-21 18:03
Mine is here

[gdb.log](https://github.com/facebookresearch/wav2letter/files/4092763/gdb.log)

**Comment by mortont** [comment] 2020-01-21 20:39
I was able to fix my issue by removing the KenLM and wav2letter build directories and then rebuilding everything fresh. My KenLM hash is `b9f35777d112ce2fc10bd3986302517a16dc3883` and my wav2letter hash is `43c42785e091f6042776555070cafc2b5255f3e2`. Not sure how it got into that state but seems to be fixed now?

**Comment by raghaviravi92** [comment] 2020-01-22 16:10
> Mine is here
> 
> [gdb.log](https://github.com/facebookresearch/wav2letter/files/4092763/gdb.log)

Were you able to fix it.. I'm facing the same issue. Used docker image for installation

**Comment by raghaviravi92** [comment] 2020-01-22 16:19
> I was able to fix my issue by removing the KenLM and wav2letter build directories and then rebuilding everything fresh. My KenLM hash is `b9f35777d112ce2fc10bd3986302517a16dc3883` and my wav2letter hash is `43c42785e091f6042776555070cafc2b5255f3e2`. Not sure how it got into that state but seems to be fixed now?



> I did not see this error before.
> Please run in gdb and send me the stack trace.
> 
> You can build the inference with fewer dependencies following https://github.com/facebookresearch/wav2letter/wiki/Inference-Run-Examples
> I would try that and see is it gets you forward.

Encountered same issue. Tried rebuilding but facing the below issue. Unable to run the simple example:

[100%] Linking CXX executable simple_streaming_asr_example
/usr/bin/ld: ../module/fbgemm/src/fbgemm/cpuinfo/libcpuinfo.a(init.c.o): undefined reference to symbol 'pthread_once@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
inference/inference/examples/CMakeFiles/simple_streaming_asr_example.dir/build.make:925: recipe for target 'inference/inference/examples/simple_streaming_asr_example' failed
make[3]: *** [inference/inference/examples/simple_streaming_asr_example] Error 1
CMakeFiles/Makefile2:1099: recipe for target 'inference/inference/examples/CMakeFiles/simple_streaming_asr_example.dir/all' failed
make[2]: *** [inference/inference/examples/CMakeFiles/simple_streaming_asr_example.dir/all] Error 2
CMakeFiles/Makefile2:1111: recipe for target 'inference/inference/examples/CMakeFiles/simple_streaming_asr_example.dir/rule' failed
make[1]: *** [inference/inference/examples/CMakeFiles/simple_streaming_asr_example.dir/rule] Error 2
Makefile:411: recipe for target 'simple_streaming_asr_example' failed
make: *** [simple_streaming_asr_example] Error 2

**Comment by raghaviravi92** [comment] 2020-01-22 17:50
> Did you try the instructions in the [inference tutorial](https://github.com/facebookresearch/wav2letter/wiki/Inference-Run-Examples) ?
> 
> Did you get the same error?

Sequence 
-----------
Yes, First I launched a docker with flashlight and then in the docker container manually installed other dependencies that wav2letter needs as per this guide :
[](https://github.com/facebookresearch/wav2letter/wiki/Dependencies
)

later performed the steps in inference tutorial. The very first time Cmake and make executions were successful for wav2letter. The below was the cmake command used for wav2letter
 `cmake .. -DCMAKE_BUILD_TYPE=Release -DW2L_LIBRARIES_USE_CUDA=OFF -DW2L_BUILD_INFERENCE=ON` 

When executing `make simple_streaming_asr_example`, **got the malloc.c:2401: sysmalloc: Assertion**  error.

Later, as per your suggestion tried deleting the build folder of wav2letter and ran with the below `~/wav2letter/build$> KENLM_ROOT_DIR=~/kenlm/build cmake .. -DW2L_BUILD_LIBRARIES_ONLY=ON -DW2L_BUILD_INFERENCE=ON `

getting [100%] Linking CXX executable simple_streaming_asr_example
/usr/bin/ld: ../module/fbgemm/src/fbgemm/cpuinfo/libcpuinfo.a(init.c.o): undefined reference to symbol 'pthread_once@@GLIBC_2.2.5' error

**Comment by avidov** [comment] 2020-01-22 18:05
The inference pipeline is simpler and has fewer dependencies than the training one. That is way I suggested following the inference tutorial. For example it does not need Flashlight or Arrayfire.

I will test and debug the scenario of using the inference tutorial on the Flashlight docker image. Until then I have a these suggestions:

-  Use the inference Docker image. Today or in the next few days we'll release wav2letter inference Docker image with the examples pre-built. I'll add the use instructions to the inference tutorial.  

-  Follow https://github.com/facebookresearch/wav2letter/wiki/Inference-Run-Examples without all the other dependencies listed in https://github.com/facebookresearch/wav2letter/wiki/Dependencies.

**Comment by tdeboissiere** [comment] 2020-01-22 18:51
Thanks !

I already got wav2letter to work with the Docker image by the way.

**Comment by raghaviravi92** [comment] 2020-01-22 18:55
using wav2letter cpu latest docker image worked !

**Closed** 2020-01-23 16:49 UTC

**Comment by realbaker1967** [comment] 2020-04-08 10:46
I had the same issue when trying to build **wav2letter-inference** without using images explained [here](https://github.com/facebookresearch/wav2letter/wiki/Inference-Run-Examples#download-and-build-wav2letter-inference), and could successfully build it setting **-DKENLM_MAX_ORDER=20** for both KenLM and wav2letter inference as suggested [here](https://github.com/facebookresearch/wav2letter/issues/405#issuecomment-538379051). 

I do not know if it is related but that solved my problem.

**Comment by tlikhomanenko** [comment] 2020-04-10 03:50
Hi @realbaker1967,

Thanks for reporting your working solution!

Flag `-DKENLM_MAX_ORDER=20` just specifies the support more than 6gram models inside KenLM (it defines some constant for the memory allocation for the algorithm). I guess the main thing is rebuilding kenlm.

Maybe the problem is deeper inside KenLM itself, and with this flag it is built correctly on your system.
